/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tp6;

import java.util.TreeSet;

/**
 *
 * @author Ivan
 */
public class MenuGral extends javax.swing.JFrame {
public static TreeSet<Productos> listaProductos = new TreeSet<>();
   
    public MenuGral() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jtProductos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmRubro = new javax.swing.JMenuItem();
        jmXnombre = new javax.swing.JMenuItem();
        jmPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setPreferredSize(new java.awt.Dimension(786, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jtProductos.setText("Administracion");
        jtProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtProductosActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Productos");
        jtProductos.add(jMenuItem1);

        jMenuBar1.add(jtProductos);

        jmConsultas.setText("Consultas");

        jmRubro.setText("Por Rubro");
        jmRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmRubroActionPerformed(evt);
            }
        });
        jmConsultas.add(jmRubro);

        jmXnombre.setText("Por Nombre");
        jmXnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmXnombreActionPerformed(evt);
            }
        });
        jmConsultas.add(jmXnombre);

        jmPrecio.setText("Por Precio");
        jmPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPrecioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmPrecio);

        jMenuBar1.add(jmConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtProductosActionPerformed
     escritorio.removeAll(); //
     escritorio.repaint();
     GestionProduc gdp = new GestionProduc();
     
        
        
    }//GEN-LAST:event_jtProductosActionPerformed

    private void jmRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmRubroActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        PorRubro gdp = new PorRubro();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);
    }//GEN-LAST:event_jmRubroActionPerformed

    private void jmXnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmXnombreActionPerformed
        escritorio.removeAll();// se usa para remover las ventanas emergentes 
        escritorio.repaint();
        PorNombre gdp = new PorNombre();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);
        
    }//GEN-LAST:event_jmXnombreActionPerformed

    private void jmPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPrecioActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        PorPrecio gdp = new PorPrecio();
        gdp.setVisible(true);
        escritorio.add(gdp);
        escritorio.moveToFront(gdp);
    }//GEN-LAST:event_jmPrecioActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmPrecio;
    private javax.swing.JMenuItem jmRubro;
    private javax.swing.JMenuItem jmXnombre;
    private javax.swing.JMenu jtProductos;
    // End of variables declaration//GEN-END:variables
private void cargarProductos(){
    listaProductos.add(new Productos (1,"Pure de tomate Arcor x 250gr",120,5,Categoria.COMESTIBLE));
    listaProductos.add(new Productos (2,"Arroz Marolio x 1kg",80.50,10,Categoria.COMESTIBLE));
    listaProductos.add(new Productos (3,"Gaseosa Coca-cola x 2.25L",400.50,12,Categoria.COMESTIBLE));
    listaProductos.add(new Productos (4,"Fideos Terrabusi",90.50,20,Categoria.COMESTIBLE));
    listaProductos.add(new Productos (10,"Jabon de mano x 3",220,8,Categoria.LIMPIEZA));
    listaProductos.add(new Productos (11,"Lavandina Ayudin x lt",150,15,Categoria.LIMPIEZA));
    listaProductos.add(new Productos (12,"Detergente Ala x Lt",100.50,13,Categoria.LIMPIEZA));
    listaProductos.add(new Productos (13,"Desinfectante Lisoform Aerosol",80.50,20,Categoria.LIMPIEZA));
    listaProductos.add(new Productos(20,"Perfume de Hombre",500,18,Categoria.PERFUMERIA));
    listaProductos.add(new Productos(21,"Crema corporal Nivea",280,16,Categoria.PERFUMERIA));
    listaProductos.add(new Productos(22,"Perfume de Mujer",430,14,Categoria.PERFUMERIA));
    listaProductos.add(new Productos(23,"Maquillaje",200,11,Categoria.PERFUMERIA));
   
}
}

